# Generated by Django 5.2.3 on 2025-07-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الدورة')),
                ('description', models.TextField(verbose_name='وصف الدورة')),
                ('image', models.ImageField(upload_to='courses/', verbose_name='صورة الدورة')),
            ],
        ),
    ]
