# Generated by Django 5.2.3 on 2025-07-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0002_professionalcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalcourse',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='مدة الدورة'),
        ),
        migrations.AddField(
            model_name='professionalcourse',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='سعر الدورة (ريال)'),
        ),
        migrations.AddField(
            model_name='professionalcourse',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ بداية الدورة'),
        ),
    ]
