# Generated by Django 5.2.3 on 2025-07-08 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0003_professionalcourse_duration_professionalcourse_price_and_more'),
        ('student', '0003_course_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.professionalcourse'),
        ),
    ]
